# Generated by Django 4.2.1 on 2023-05-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tutorial',
            field=models.URLField(default='https://www.youtube.com/'),
        ),
        migrations.AddField(
            model_name='stock',
            name='image',
            field=models.ImageField(default='stock/no_picture.png', upload_to='stock/'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
