# Generated by Django 4.2.1 on 2023-05-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_tutorial_stock_image_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tutorial',
            field=models.URLField(),
        ),
    ]
