# Generated by Django 4.2.1 on 2023-05-25 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_stock_shade_alter_brand_slug_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tutorial',
            field=models.URLField(blank=True, null=True),
        ),
    ]
