# Generated by Django 4.2.1 on 2023-05-25 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_tutorial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='shade',
            new_name='other',
        ),
    ]
