# Generated by Django 4.2.1 on 2023-05-26 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='views',
        ),
    ]
