# Generated by Django 4.2.1 on 2023-05-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_product_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='image',
            field=models.ImageField(default='ratings/no_picture.png', upload_to='ratings/'),
        ),
    ]
