# Generated by Django 4.2.1 on 2023-05-27 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
